### ISSUE TITLE
拖拽组件不显示

### ISSUE THREAD

**Issue by JohnnyZhang0628** [pengxiaotian/datav-vue#14]
![image](https://user-images.githubusercontent.com/28375774/119752675-0289ea80-bed0-11eb-9e63-8b0ea4417ca3.png)
你好，我在测试新建一个模板，我拖拽一个组件，不显示。不知道是不是我操作哪里有没有问题？

**Comment by pengxiaotian** [comment]
@JohnnyZhang0628 目前只有一个标题组件可以用，我刚更新了 README.md，可以看一下。
