### ISSUE TITLE
建议用prettier格式化代码

### ISSUE THREAD

**Issue by liuzhidong0918** [pengxiaotian/datav-vue#17]
因为不同编辑器的格式化不一样,保存后和项目不一致

**Comment by pengxiaotian** [comment]
我用的是 eslint + stylelint + editorconfig 配合 vscode 很爽啊。
并且我也不喜欢 prettier 格式化后的代码。

**Comment by liuzhidong0918** [comment]
嗯嗯  因为代码clone下来 我并没找到你格式化代码所需要的工具，经过你的提醒，下了editorconfig 插件可以跟项目匹配了
