### ISSUE TITLE
标尺问题

### ISSUE THREAD

**Issue by gongym12138** [pengxiaotian/datav-vue#22]
https://user-images.githubusercontent.com/20694755/122205446-d3650880-ced2-11eb-90c3-ef78eef46696.mp4

注意看两个箭头指的位置，拖动时会有虚线在0的位置显示

![image](https://user-images.githubusercontent.com/20694755/122205635-10c99600-ced3-11eb-9f6e-77b462ab7ab0.png)

**Comment by pengxiaotian** [comment]
手抖了 commit 写了个 #123 😣
