### ISSUE TITLE
去年基于react做了个类似的项目，部分Feature可以交流一下

### ISSUE THREAD

**Issue by realeve** [pengxiaotian/datav-vue#25]
![image](https://user-images.githubusercontent.com/448208/127001663-8a4ec79f-30e1-4730-9270-9cf2db77d269.png)

![image](https://user-images.githubusercontent.com/448208/127001791-12e0346e-79cf-4e05-930d-c228fc131c51.png)

![image](https://user-images.githubusercontent.com/448208/127003452-481a94a7-62cf-49b4-917e-dee3c5f95805.png)

**Comment by pengxiaotian** [comment]
突然不想做了。。。用你的不香么😂
