### ISSUE TITLE
ele的switch开关的样式貌似出问题

### ISSUE THREAD

**Issue by zhangfeng158** [pengxiaotian/datav-vue#26]
![image](https://user-images.githubusercontent.com/33825898/127249519-1610ecb5-3e60-4d24-8baa-7417885d9669.png)

**Comment by pengxiaotian** [comment]
这是本地还是线上？

**Comment by zhangfeng158** [comment]
本地的，线上的是好的

**Comment by pengxiaotian** [comment]
初始化项目时要用：`yarn bootstrap` 或者 `yarn --frozen-lockfile`

element-plus 从beta56 开始正在重构 css，还没稳定，不要升级它

**Comment by zhangfeng158** [comment]
嗯，好的，感谢感谢
