### ISSUE TITLE
请问前端用的是element-plus框架吗？

### ISSUE THREAD

**Issue by laopeng2021** [pengxiaotian/datav-vue#32]
element-plus是VUE3.0的。
请问你这个前端用的是哪个？谢谢

**Comment by pengxiaotian** [comment]
> 为什么用两套？ 用一套element plus或者Naive UI不行吗？ 谢谢

除了 `el-tabs` 之外, 其他都是 `naive-ui`

`naive-ui` 的 `n-tabs` 只有横向的 没有纵向。

**Comment by pengxiaotian** [comment]
相关跟踪： https://github.com/TuSimple/naive-ui/issues/1466
