### ISSUE TITLE
  @Module 语法无法识别

### ISSUE THREAD

**Issue by zhangle1** [pengxiaotian/datav-vue#34]
大佬请教下 ，我模仿你的写法 ，去安装vuex-module-decorators 这个库，
但是   @Module({ dynamic: true, store, name: 'toolbar' })
这一行 提示我报错   此语法需要一个导入的帮助程序，但找不到模块“tslib”。ts(2354) ,这个我是缺少引入什么吗

**Comment by pengxiaotian** [comment]
删掉 node_modules 目录， 使用`yarn bootstrap` 初始化项目。
