### ISSUE TITLE
项目里面使用到了dataV插件了吗？package.json没看到对应的版本信息

### ISSUE THREAD

**Issue by xuezhangGit** [pengxiaotian/datav-vue#45]

**Comment by pengxiaotian** [comment]
dataV插件 什么鬼？

**Comment by DyncKathline** [comment]
> dataV插件 什么鬼？

这个，我觉得也希望集成进去，效果更炫
https://github.com/DataV-Team/DataV

**Comment by pengxiaotian** [comment]
> > dataV插件 什么鬼？
> 
> 这个，我觉得也希望集成进去，效果更炫 https://github.com/DataV-Team/DataV

他这个里面的组件不满足我的需求，你可以在自己的项目里加上。
