### ISSUE TITLE
组合、拆分

### ISSUE THREAD

**Issue by yiweizhi** [pengxiaotian/datav-vue#47]
一直在关注这个项目，卡在组合和拆分这里了。有下一步开发计划吗？希望大神提供下这个功能的开发思路，感谢！

**Comment by pengxiaotian** [comment]
> 一直在关注这个项目，卡在组合和拆分这里了。有下一步开发计划吗？希望大神提供下这个功能的开发思路，感谢！

下一步计划就是做这个功能，隔离之后心情很糟糕 好久了 😞

**Comment by 312837310** [comment]
> 下一步计划就是做这个功能，隔离之后心情很糟糕 好久了 😞

加油，希望作者调整好心态；我也一直再关注这个项目，分组和撤销对于配置大屏来说，确实是一个刚需功能，期待！

**Comment by yiweizhi** [comment]
> 下一步计划就是做这个功能，隔离之后心情很糟糕 好久了 😞

**Comment by hawind** [comment]
确实好项目，希望完善
