### ISSUE TITLE
组件的获取、删除、新增、复制是用在什么地方呢？

### ISSUE THREAD

**Issue by yiweizhi** [pengxiaotian/datav-vue#48]
export function getComs(projectId: number) {
  return request.get('/coms', { params: { projectId } })
}

export function deleteCom(id: string) {
  return request.delete(`/coms/${id}`)
}

export function addCom(data: any) {
  return request.post('/coms', data)
}

export function copyCom(id: string) {
  return request.post(`/coms/${id}/copy`)
}

我看代码中有组件的相关请求，主要是怎么运用的，因为操作时不依赖后端数据，大屏保存的时候将最终的数据存在库了就行了吧。

**Comment by pengxiaotian** [comment]
你可以全局搜索一下啊。
