### ISSUE TITLE
可以和您一起补全这各项目吗？

### ISSUE THREAD

**Issue by ID-LiuDaZhi** [pengxiaotian/datav-vue#51]
我希望和您一起补全这个项目

**Comment by pengxiaotian** [comment]
目前计划是学习一些前端知识，然后自己把1.0的功能清单自己做完，就当是练手了，这对我来说很有意义。只不过最近大半年生活琐事太多了，一直没跟进。

**Comment by ZedCoding** [comment]
迫切期待1.0发布

**Comment by hahahaooo** [comment]
带你飞老哥！！！[2414741098@qq.com](url)
