### ISSUE TITLE
请问有完整的schema说明吗

### ISSUE THREAD

**Issue by fancyboynet** [pengxiaotian/datav-vue#55]

**Comment by pengxiaotian** [comment]
没有

**Comment by lingyan2016** [comment]
请问完整的版本出来了吗？谢谢！！

**Comment by pengxiaotian** [comment]
> 请问完整的版本出来了吗？谢谢！！

正在挤时间做

**Comment by lingyan2016** [comment]
感谢大神。。数据部分能不能增加sql调取。谢谢


期待完整版。持续关注中。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月29日(周三) 下午5:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pengxiaotian/datav-vue] 请问有完整的schema说明吗 (Issue #55)




  
请问完整的版本出来了吗？谢谢！！
  
正在挤时间做

**Comment by fancyboynet** [comment]
> 没有

可以的话希望可以给一个完成的JSON说明，让人可以更快地了解整个架构设计和上手，感谢
