### ISSUE TITLE
请问可用版什么时候才能发布

### ISSUE THREAD

**Issue by lingyan2016** [pengxiaotian/datav-vue#60]
你好，请问可用版什么时候才能发布？谢谢

**Comment by pengxiaotian** [comment]
额... 其实现在就能用了，我上周已经把基础操作交互开发完了，剩下的就是丰富组件了，组件列表在文档有写。
组件肯定满足不了所有人。。

**Comment by pengxiaotian** [comment]
最近在阅读高德和百度地图的 API，真恶心

**Comment by lingyan2016** [comment]
数据交互完了吗？求大神丰富组件，让这个作品更完美。谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月4日(周四) 凌晨0:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pengxiaotian/datav-vue] 请问可用版什么时候才能发布 (Issue #60)




 
额... 其实现在就能用了，我上周已经把基础操作交互开发完了，剩下的就是丰富组件了，组件列表在文档有写。
 组件肯定满足不了所有人。。

**Comment by lingyan2016** [comment]
数据和组件部分还是显示在建设，求大神完善这个很好的项目



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月4日(周四) 凌晨0:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pengxiaotian/datav-vue] 请问可用版什么时候才能发布 (Issue #60)




 
最近在阅读高德和百度地图的 API，真恶心
