### ISSUE TITLE
撤销重做功能

### ISSUE THREAD

**Issue by 312837310** [pengxiaotian/datav-vue#69]
您好：

关于编辑器的撤销重做功能，我看有这部分的代码，但是标记了弃用，
想问下这个功能有计划优化吗？对于配置人员来说，这个功能太重要了；

![image](https://user-images.githubusercontent.com/12478715/206845932-0a72fb84-f703-4964-b430-5869242782b6.png)

期待回复，非常感谢

**Comment by pengxiaotian** [comment]
考虑到页面的组件数量和每个组件的数据量, 如果支持撤销重做,页面太卡了, 没啥好的优化方案, 以后有机会在说.

**Comment by wsxe9988** [comment]
@pengxiaotian 可以参考https://gitee.com/dromara/go-view 地址里的撤销回退的思路看看

**Comment by pengxiaotian** [comment]
一样, 都是放内存里.
