### ISSUE TITLE
太牛了，什么时候能把数据源和数据集的功能加上呢，大佬？

### ISSUE THREAD

**Issue by rogerjsw** [pengxiaotian/datav-vue#71]
刚刚使用了大佬的更新，地图功能真的很棒。
1、但是发现一个问题：飞线层---耀斑样式----设置“类型“不起作用，需要每次打开、关闭“耀斑样式”按钮才起作用，希望能修复一下。
2、什么时候能把数据源和数据集的功能加上呢？
期待大佬的回复，静候中。。。

**Comment by pengxiaotian** [comment]
什么数据集？

**Comment by pengxiaotian** [comment]
不生效是echarts合并bug...

**Comment by rogerjsw** [comment]
> 什么数据集？

就像阿里datav的数据源、数据集功能，我只是问问。
![我的数据](https://user-images.githubusercontent.com/120232384/206886518-9d5382b4-d404-4be4-80a8-90cfbf371474.png)

**Comment by rogerjsw** [comment]
不知大佬接下来有什么更新、发布计划？好期待，这个项目真的很牛
