### ISSUE TITLE
过滤器保存功能有问题

### ISSUE THREAD

**Issue by rogerjsw** [pengxiaotian/datav-vue#75]
老大，过滤器保存功能有问题，具体如下：
1、过滤器名称改过，但是传到后端后名称还是“新建过滤器”
2、projectId一直为0，不是所在的项目id
请老大有空时看一下，谢谢。

![image](https://user-images.githubusercontent.com/120232384/210055537-0deca3eb-217a-4e11-9a8d-8d1f14e4e9d6.png)

**Comment by pengxiaotian** [comment]
名称可以改的没发现bug, 
projectId 写死了 0

**Comment by rogerjsw** [comment]
> 名称可以改的没发现bug, projectId 写死了 0

修改名称后，点击保存快照，然后再打开过滤器列表，你会发现名称还是“新建过滤器”

**Comment by pengxiaotian** [comment]
复现不了

**Comment by rogerjsw** [comment]
> 复现不了

大佬，保存时把projectId写死了为0，但是取的时候是根据实际值来取
const res = await api.getFilters(projectId)
导致查询出来的过滤器列表里不会有数据的
