### ISSUE TITLE
两个组件叠在一起，点击不准

### ISSUE THREAD

**Issue by wsxe9988** [pengxiaotian/datav-vue#76]
![image](https://user-images.githubusercontent.com/5828057/210768328-02a4969c-466b-4094-a5d4-9d2d27bdc68a.png)
https://datav.pengxiaotian.com/#/admin/screen/1?tpl=1

示例界面：词云图和多行文本组件叠在一起，先放词云图，再放多行文本组件上去，点中的都是词云图

**Comment by pengxiaotian** [comment]
你调整一下图层的顺序

**Comment by wsxe9988** [comment]
调整了，还是不行

**Comment by wsxe9988** [comment]
可以了
